server:
  port: 9000

spring:
  application:
    name: eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
